version: '2'
services:
  web:
    build: .
    volumes:
     - ./application:/application
    links:
     - redis
    expose:
     - "5000"
  redis:
    image: redis
  lb:
    image: dockercloud/haproxy
    environment:
      - BACKEND_PORT=5000
      - BALANCE=roundrobin
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80